# Generated by Django 6.0.1 on 2026-02-22 13:10

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(help_text='Original filename', max_length=500)),
                ('file_type', models.CharField(choices=[('pdf', 'PDF'), ('docx', 'DOCX'), ('txt', 'TXT')], max_length=10)),
                ('file', models.FileField(blank=True, help_text='Original file (may be deleted after processing)', null=True, upload_to='documents/%Y/%m/%d/')),
                ('file_size', models.PositiveIntegerField(default=0, help_text='File size in bytes')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('processing', 'Processing'), ('completed', 'Completed'), ('failed', 'Failed')], default='pending', max_length=20)),
                ('error_message', models.TextField(blank=True, null=True)),
                ('total_chunks', models.PositiveIntegerField(default=0)),
                ('total_characters', models.PositiveIntegerField(default=0)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('processed_at', models.DateTimeField(blank=True, null=True)),
                ('uploaded_by', models.ForeignKey(blank=True, db_column='uploaded_by_id', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='uploaded_documents', to='users.user')),
            ],
            options={
                'ordering': ['-uploaded_at'],
            },
        ),
        migrations.CreateModel(
            name='AnalysisResult',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('checklist_id', models.IntegerField(help_text='ID of the ISO 27001 checklist item')),
                ('checklist_title', models.CharField(help_text='Title of the checklist item', max_length=500)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('processing', 'Processing'), ('completed', 'Completed'), ('failed', 'Failed')], default='pending', max_length=20)),
                ('compliance_status', models.CharField(blank=True, choices=[('compliant', 'Compliant'), ('partial', 'Partially Compliant'), ('non_compliant', 'Non-Compliant'), ('not_applicable', 'Not Applicable')], max_length=20, null=True)),
                ('compliance_score', models.FloatField(default=0.0, help_text='Compliance score from 0.0 to 1.0')),
                ('summary', models.TextField(blank=True, help_text='AI-generated summary of the analysis')),
                ('findings', models.JSONField(default=list, help_text='List of specific findings')),
                ('recommendations', models.JSONField(default=list, help_text='List of recommendations for improvement')),
                ('gaps', models.JSONField(default=list, help_text='List of compliance gaps identified')),
                ('comments', models.JSONField(default=list, help_text='General comments and observations about the audit report')),
                ('control_scores', models.JSONField(default=dict, help_text='Individual scores for each control (control_name: score)')),
                ('error_message', models.TextField(blank=True, null=True)),
                ('pdf_report', models.FileField(blank=True, help_text='AI-generated PDF audit report', max_length=255, null=True, upload_to='reports/%Y/%m/%d/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('analyzed_by', models.ForeignKey(blank=True, db_column='analyzed_by_id', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='analyses', to='users.user')),
                ('documents', models.ManyToManyField(blank=True, related_name='analysis_results', to='documents.document')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='DocumentChunk',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('content', models.TextField(help_text='The actual text content of the chunk')),
                ('chunk_index', models.PositiveIntegerField(help_text='Order of this chunk in the document')),
                ('start_char', models.PositiveIntegerField(default=0, help_text='Starting character position in original document')),
                ('end_char', models.PositiveIntegerField(default=0, help_text='Ending character position in original document')),
                ('char_count', models.PositiveIntegerField(default=0)),
                ('word_count', models.PositiveIntegerField(default=0)),
                ('heading', models.CharField(blank=True, max_length=500, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chunks', to='documents.document')),
            ],
            options={
                'ordering': ['document', 'chunk_index'],
            },
        ),
        migrations.AddIndex(
            model_name='document',
            index=models.Index(fields=['status'], name='documents_d_status_07369e_idx'),
        ),
        migrations.AddIndex(
            model_name='document',
            index=models.Index(fields=['file_type'], name='documents_d_file_ty_1bb410_idx'),
        ),
        migrations.AddIndex(
            model_name='document',
            index=models.Index(fields=['uploaded_at'], name='documents_d_uploade_65506e_idx'),
        ),
        migrations.AddIndex(
            model_name='analysisresult',
            index=models.Index(fields=['checklist_id'], name='documents_a_checkli_59076f_idx'),
        ),
        migrations.AddIndex(
            model_name='analysisresult',
            index=models.Index(fields=['status'], name='documents_a_status_91b1b2_idx'),
        ),
        migrations.AddIndex(
            model_name='analysisresult',
            index=models.Index(fields=['compliance_status'], name='documents_a_complia_b921f3_idx'),
        ),
        migrations.AddIndex(
            model_name='analysisresult',
            index=models.Index(fields=['created_at'], name='documents_a_created_be7710_idx'),
        ),
        migrations.AddIndex(
            model_name='documentchunk',
            index=models.Index(fields=['document', 'chunk_index'], name='documents_d_documen_8ea6ce_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='documentchunk',
            unique_together={('document', 'chunk_index')},
        ),
    ]
