# Generated by Django 6.0.1 on 2026-02-12 05:23

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AnalysisResult',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('checklist_id', models.IntegerField(help_text='ID of the ISO 27001 checklist item')),
                ('checklist_title', models.CharField(help_text='Title of the checklist item', max_length=500)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('processing', 'Processing'), ('completed', 'Completed'), ('failed', 'Failed')], default='pending', max_length=20)),
                ('compliance_status', models.CharField(blank=True, choices=[('compliant', 'Compliant'), ('partial', 'Partially Compliant'), ('non_compliant', 'Non-Compliant'), ('not_applicable', 'Not Applicable')], max_length=20, null=True)),
                ('compliance_score', models.FloatField(default=0.0, help_text='Compliance score from 0.0 to 1.0')),
                ('summary', models.TextField(blank=True, help_text='AI-generated summary of the analysis')),
                ('findings', models.JSONField(default=list, help_text='List of specific findings')),
                ('recommendations', models.JSONField(default=list, help_text='List of recommendations for improvement')),
                ('gaps', models.JSONField(default=list, help_text='List of compliance gaps identified')),
                ('error_message', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('analyzed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='analyses', to=settings.AUTH_USER_MODEL)),
                ('documents', models.ManyToManyField(blank=True, related_name='analysis_results', to='documents.document')),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['checklist_id'], name='documents_a_checkli_59076f_idx'), models.Index(fields=['status'], name='documents_a_status_91b1b2_idx'), models.Index(fields=['compliance_status'], name='documents_a_complia_b921f3_idx'), models.Index(fields=['created_at'], name='documents_a_created_be7710_idx')],
            },
        ),
    ]
