# Generated by Django 6.0.1 on 2026-02-13 05:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0002_analysisresult'),
    ]

    operations = [
        migrations.AddField(
            model_name='analysisresult',
            name='comments',
            field=models.JSONField(default=list, help_text='General comments and observations about the audit report'),
        ),
        migrations.AddField(
            model_name='analysisresult',
            name='control_scores',
            field=models.JSONField(default=dict, help_text='Individual scores for each control (control_name: score)'),
        ),
    ]
