# Generated by Django 6.0.1 on 2026-02-20 06:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0003_analysisresult_comments_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='analysisresult',
            name='pdf_report',
            field=models.FileField(blank=True, help_text='AI-generated PDF audit report', null=True, upload_to='reports/%Y/%m/%d/'),
        ),
    ]
