# Generated by Django 6.0.1 on 2026-02-20 11:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0004_analysisresult_pdf_report'),
    ]

    operations = [
        migrations.AlterField(
            model_name='analysisresult',
            name='pdf_report',
            field=models.FileField(blank=True, help_text='AI-generated PDF audit report', max_length=255, null=True, upload_to='reports/%Y/%m/%d/'),
        ),
    ]
